# Generated by Django 4.2.29 on 2026-03-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Autobiography', 'Autobiography'), ('Fantasy', 'Fantasy'), ("Children's", "Children's"), ('Mystery', 'Mystery'), ('Trashy', 'Trashy'), ('Drama', 'Drama'), ('Humor', 'Humor'), ('Science Fiction', 'Science Fiction'), ('Non-Fiction', 'Non-Fiction'), ('Political memoir', 'Political memoir'), ('Historical', 'Historical'), ('Satire', 'Satire'), ('Vaudeville', 'Vaudeville'), ('Biography', 'Biography'), ('Poetry', 'Poetry'), ('Horror', 'Horror'), ('Sports', 'Sports'), ('Fiction', 'Fiction')], max_length=40),
        ),
    ]
