# Generated by Django 4.2.29 on 2026-03-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookshop", "0002_alter_book_genre"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="price",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
