# Generated by Django 4.2.29 on 2026-03-14 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0003_order_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='price',
            new_name='total',
        ),
    ]
