# Generated by Django 4.2.29 on 2026-03-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0005_alter_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='availability',
            field=models.IntegerField(choices=[('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable')], default=1),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('AUTOBIOGRAPHY', 'Autobiography'), ('FANTASY', 'Fantasy'), ('CHILDRENS', "Children's"), ('MYSTERY', 'Mystery'), ('TRASHY', 'Trashy'), ('DRAMA', 'Drama'), ('HUMOR', 'Humor'), ('SCI_FI', 'Science Fiction'), ('NON_FICTION', 'Non-Fiction'), ('POLITICAL_MEMOIR', 'Political memoir'), ('HISTORICAL', 'Historical'), ('SATIRE', 'Satire'), ('VAUDEVILLE', 'Vaudeville'), ('BIOGRAPHY', 'Biography'), ('POETRY', 'Poetry'), ('HORROR', 'Horror'), ('SPORTS', 'Sports'), ('FICTION', 'Fiction')], max_length=40),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.IntegerField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived'), ('SUSPENDED', 'Suspended')], default=0),
        ),
    ]
