# Generated by Django 4.2.29 on 2026-05-13 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0008_remove_order_total_alter_book_availability_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='price',
            new_name='unit_price',
        ),
    ]
