# Generated by Django 4.2.29 on 2026-05-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0009_rename_price_book_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='line_total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
