# Generated by Django 4.2.29 on 2026-05-13 13:42

from django.db import migrations
from django.db.models import F

def backfill(apps, schema_editor):
    OrderItem = apps.get_model('bookshop', 'OrderItem')
    items = OrderItem.objects.select_related('book')
    for item in items:
        item.line_total = item.quantity * item.book.unit_price
    OrderItem.objects.bulk_update(items, ['line_total'], batch_size=1000)

class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0010_order_total_price_orderitem_line_total'),
    ]

    operations = [
        migrations.RunPython(backfill),
    ]
