# Generated by Django 4.2.29 on 2026-05-13 13:44

from django.db import migrations

def backfill(apps, schema_editor):
    Order = apps.get_model('bookshop', 'Order')
    orders = Order.objects.prefetch_related('items')
    for order in orders:
        order.total_price = sum(item.line_total for item in order.items.all())
    Order.objects.bulk_update(orders, ['total_price'], batch_size=1000)

class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0011_backfill_orderitem_line_total'),
    ]

    operations = [
        migrations.RunPython(backfill),
    ]
